AWSTemplateFormatVersion: "2010-09-09"
Description: Create an EC2 instance

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0a0c8eebcdd6dcbd0  
      KeyName: n.virginia-keypair
